name: c2pa_view_example
description: "Demonstrates how to use the c2pa_view plugin."
publish_to: 'none'

# Version
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  c2pa_view:
    # When depending on this package from a real application you should use:
    #   c2pa_view: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # HTTP package for making network requests
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Test data
  assets:
    - assets/c2pa_test_data.dsv
