// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:c2pa_view/src/rust/api/c2pa.dart';
import 'package:c2pa_view/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(final raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(final raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(final raw);

  @protected
  String? dco_decode_opt_String(final raw);

  @protected
  int dco_decode_u_8(final raw);

  @protected
  String sse_decode_String(final SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(final SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(final SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(final SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(final SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(final SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(final SseDeserializer deserializer);

  @protected
  void sse_encode_String(final String self, final SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(final List<int> self, final SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    final Uint8List self,
    final SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(final String? self, final SseSerializer serializer);

  @protected
  void sse_encode_u_8(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_i_32(final int self, final SseSerializer serializer);

  @protected
  void sse_encode_bool(final bool self, final SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
