// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/c2pa.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1291742180;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'c2pa_view',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String?> crateApiC2PaGetDetachedManifestWithTrustValidation({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
    required String trustAnchorsPem,
  });

  Future<Uint8List?> crateApiC2PaGetDetachedManifestWithTrustValidationUtf8({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
    required String trustAnchorsPem,
  });

  Future<String?> crateApiC2PaGetDetachedManifestWithValidation({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
  });

  Future<Uint8List?> crateApiC2PaGetDetachedManifestWithValidationUtf8({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
  });

  Future<String?> crateApiC2PaGetFileManifest({
    required List<int> fileBytes,
    required String path,
  });

  Future<String?> crateApiC2PaGetFileManifestFormat({
    required List<int> fileBytes,
    required String format,
  });

  Future<Uint8List?> crateApiC2PaGetFileManifestFormatUtf8({
    required List<int> fileBytes,
    required String format,
  });

  Future<String?> crateApiC2PaGetManifestWithTrustValidation({
    required List<int> fileBytes,
    required String format,
    required String trustAnchorsPem,
  });

  Future<String?> crateApiC2PaGetManifestWithTrustValidationFromPath({
    required String path,
    required String trustAnchorsPem,
  });

  Future<String?> crateApiC2PaGetManifestWithValidation({
    required List<int> fileBytes,
    required String format,
  });

  Future<String?> crateApiC2PaGetManifestWithValidationFromPath({
    required String path,
  });

  Future<Uint8List?> crateApiC2PaGetManifestWithValidationUtf8({
    required List<int> fileBytes,
    required String format,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String?> crateApiC2PaGetDetachedManifestWithTrustValidation({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
    required String trustAnchorsPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(manifestBytes, serializer);
          sse_encode_String(manifestFormat, serializer);
          sse_encode_list_prim_u_8_loose(assetBytes, serializer);
          sse_encode_String(assetFormat, serializer);
          sse_encode_String(trustAnchorsPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetDetachedManifestWithTrustValidationConstMeta,
        argValues: [
          manifestBytes,
          manifestFormat,
          assetBytes,
          assetFormat,
          trustAnchorsPem,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiC2PaGetDetachedManifestWithTrustValidationConstMeta =>
      const TaskConstMeta(
        debugName: "get_detached_manifest_with_trust_validation",
        argNames: [
          "manifestBytes",
          "manifestFormat",
          "assetBytes",
          "assetFormat",
          "trustAnchorsPem",
        ],
      );

  @override
  Future<Uint8List?> crateApiC2PaGetDetachedManifestWithTrustValidationUtf8({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
    required String trustAnchorsPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(manifestBytes, serializer);
          sse_encode_String(manifestFormat, serializer);
          sse_encode_list_prim_u_8_loose(assetBytes, serializer);
          sse_encode_String(assetFormat, serializer);
          sse_encode_String(trustAnchorsPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiC2PaGetDetachedManifestWithTrustValidationUtf8ConstMeta,
        argValues: [
          manifestBytes,
          manifestFormat,
          assetBytes,
          assetFormat,
          trustAnchorsPem,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiC2PaGetDetachedManifestWithTrustValidationUtf8ConstMeta =>
      const TaskConstMeta(
        debugName: "get_detached_manifest_with_trust_validation_utf8",
        argNames: [
          "manifestBytes",
          "manifestFormat",
          "assetBytes",
          "assetFormat",
          "trustAnchorsPem",
        ],
      );

  @override
  Future<String?> crateApiC2PaGetDetachedManifestWithValidation({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(manifestBytes, serializer);
          sse_encode_String(manifestFormat, serializer);
          sse_encode_list_prim_u_8_loose(assetBytes, serializer);
          sse_encode_String(assetFormat, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetDetachedManifestWithValidationConstMeta,
        argValues: [manifestBytes, manifestFormat, assetBytes, assetFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetDetachedManifestWithValidationConstMeta =>
      const TaskConstMeta(
        debugName: "get_detached_manifest_with_validation",
        argNames: [
          "manifestBytes",
          "manifestFormat",
          "assetBytes",
          "assetFormat",
        ],
      );

  @override
  Future<Uint8List?> crateApiC2PaGetDetachedManifestWithValidationUtf8({
    required List<int> manifestBytes,
    required String manifestFormat,
    required List<int> assetBytes,
    required String assetFormat,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(manifestBytes, serializer);
          sse_encode_String(manifestFormat, serializer);
          sse_encode_list_prim_u_8_loose(assetBytes, serializer);
          sse_encode_String(assetFormat, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetDetachedManifestWithValidationUtf8ConstMeta,
        argValues: [manifestBytes, manifestFormat, assetBytes, assetFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiC2PaGetDetachedManifestWithValidationUtf8ConstMeta =>
      const TaskConstMeta(
        debugName: "get_detached_manifest_with_validation_utf8",
        argNames: [
          "manifestBytes",
          "manifestFormat",
          "assetBytes",
          "assetFormat",
        ],
      );

  @override
  Future<String?> crateApiC2PaGetFileManifest({
    required List<int> fileBytes,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetFileManifestConstMeta,
        argValues: [fileBytes, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetFileManifestConstMeta =>
      const TaskConstMeta(
        debugName: "get_file_manifest",
        argNames: ["fileBytes", "path"],
      );

  @override
  Future<String?> crateApiC2PaGetFileManifestFormat({
    required List<int> fileBytes,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetFileManifestFormatConstMeta,
        argValues: [fileBytes, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetFileManifestFormatConstMeta =>
      const TaskConstMeta(
        debugName: "get_file_manifest_format",
        argNames: ["fileBytes", "format"],
      );

  @override
  Future<Uint8List?> crateApiC2PaGetFileManifestFormatUtf8({
    required List<int> fileBytes,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetFileManifestFormatUtf8ConstMeta,
        argValues: [fileBytes, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetFileManifestFormatUtf8ConstMeta =>
      const TaskConstMeta(
        debugName: "get_file_manifest_format_utf8",
        argNames: ["fileBytes", "format"],
      );

  @override
  Future<String?> crateApiC2PaGetManifestWithTrustValidation({
    required List<int> fileBytes,
    required String format,
    required String trustAnchorsPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(format, serializer);
          sse_encode_String(trustAnchorsPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetManifestWithTrustValidationConstMeta,
        argValues: [fileBytes, format, trustAnchorsPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetManifestWithTrustValidationConstMeta =>
      const TaskConstMeta(
        debugName: "get_manifest_with_trust_validation",
        argNames: ["fileBytes", "format", "trustAnchorsPem"],
      );

  @override
  Future<String?> crateApiC2PaGetManifestWithTrustValidationFromPath({
    required String path,
    required String trustAnchorsPem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(trustAnchorsPem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetManifestWithTrustValidationFromPathConstMeta,
        argValues: [path, trustAnchorsPem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiC2PaGetManifestWithTrustValidationFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "get_manifest_with_trust_validation_from_path",
        argNames: ["path", "trustAnchorsPem"],
      );

  @override
  Future<String?> crateApiC2PaGetManifestWithValidation({
    required List<int> fileBytes,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetManifestWithValidationConstMeta,
        argValues: [fileBytes, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetManifestWithValidationConstMeta =>
      const TaskConstMeta(
        debugName: "get_manifest_with_validation",
        argNames: ["fileBytes", "format"],
      );

  @override
  Future<String?> crateApiC2PaGetManifestWithValidationFromPath({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetManifestWithValidationFromPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetManifestWithValidationFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "get_manifest_with_validation_from_path",
        argNames: ["path"],
      );

  @override
  Future<Uint8List?> crateApiC2PaGetManifestWithValidationUtf8({
    required List<int> fileBytes,
    required String format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(format, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiC2PaGetManifestWithValidationUtf8ConstMeta,
        argValues: [fileBytes, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiC2PaGetManifestWithValidationUtf8ConstMeta =>
      const TaskConstMeta(
        debugName: "get_manifest_with_validation_utf8",
        argNames: ["fileBytes", "format"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
