name: c2pa_manifest_viewer_example
description: Example app showcasing the c2pa_manifest_viewer package.
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  c2pa_manifest_viewer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
