#!/usr/bin/env python3
"""Generate corpus.manifest.json for the C2PA conformance sample directory.

The manifest records the snapshot source (the official C2PA Drive folder
plus any self-provided samples), the snapshot date, and per-file SHA-256
hashes for every media file. Reviewers can use the manifest to verify
that the corpus they downloaded matches the corpus that produced the
validator evidence report.

The manifest is regenerated by `rerun-validation.sh` on every run, so it
always reflects the current contents of `conformance-samples/`.

Snapshot status:
  - "pending-drive-refresh" (default): the corpus is still the InReality
    local snapshot from before the conformance program's Drive-corpus
    requirement landed. Per-file source = "InReality local snapshot".
  - "conformant": the operator has replaced the directory with the
    official c2pa-org/conformance-public Drive corpus. Per-file source
    = the Drive label. To declare this state, drop a marker file named
    ".drive-refreshed" alongside the sample files; the script detects
    it automatically.

HEIC/HEIF files are always labelled self-provided (the program's Drive
folder has no HEIC samples; we ship our own with explicit approval).

Usage: generate-corpus-manifest.py <conformance-samples-dir>
"""

from __future__ import annotations

import hashlib
import json
import sys
from datetime import date
from pathlib import Path

DRIVE_FOLDER_URL = (
    "https://drive.google.com/drive/folders/"
    "1TCSjsDGp5g6vx37oSiry2lHHpVNq7zct"
)
DRIVE_SOURCE_LABEL = "c2pa-org/conformance-public Drive"
LOCAL_SOURCE_LABEL = "InReality local snapshot (pre-conformance-refresh)"
SELF_PROVIDED_LABEL = "InReality (self-provided)"
DRIVE_MARKER_FILENAME = ".drive-refreshed"
MEDIA_EXTENSIONS = {
    "jpg",
    "jpeg",
    "png",
    "dng",
    "heic",
    "heif",
    "mp4",
    "m4v",
    "m4a",
    "mov",
}


def sha256_of(path: Path) -> str:
    """Compute the SHA-256 of a file as a lowercase hex string."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    samples_dir = Path(argv[1]).resolve()
    if not samples_dir.is_dir():
        print(f"not a directory: {samples_dir}", file=sys.stderr)
        return 2

    drive_refreshed = (samples_dir / DRIVE_MARKER_FILENAME).exists()
    snapshot_status = "conformant" if drive_refreshed else "pending-drive-refresh"
    default_source = (
        DRIVE_SOURCE_LABEL if drive_refreshed else LOCAL_SOURCE_LABEL
    )

    files = []
    for entry in sorted(samples_dir.iterdir()):
        if not entry.is_file():
            continue
        ext = entry.suffix.lower().lstrip(".")
        if ext not in MEDIA_EXTENSIONS:
            continue
        if ext in ("heic", "heif"):
            source = SELF_PROVIDED_LABEL
            note = (
                "HEIC/HEIF sample not provided in the Drive corpus; "
                "supplied by InReality with explicit conformance approval."
            )
        else:
            source = default_source
            note = ""
        record = {
            "name": entry.name,
            "size_bytes": entry.stat().st_size,
            "sha256": sha256_of(entry),
            "source": source,
        }
        if note:
            record["note"] = note
        files.append(record)

    manifest = {
        "snapshot_date": date.today().isoformat(),
        "snapshot_status": snapshot_status,
        "snapshot_status_note": (
            "Drop a `.drive-refreshed` marker file in the samples directory "
            "after replacing it with the official c2pa-org/conformance-public "
            "Drive corpus, then re-run scripts/rerun-validation.sh."
        ),
        "drive_folder_url": DRIVE_FOLDER_URL,
        "drive_source_label": DRIVE_SOURCE_LABEL,
        "local_source_label": LOCAL_SOURCE_LABEL,
        "self_provided_label": SELF_PROVIDED_LABEL,
        "self_provided_note": (
            "Files marked with the self-provided source are not part of "
            "the c2pa-org/conformance-public Drive folder; they are "
            "supplied by InReality (HEIC samples) with explicit approval "
            "from the conformance program."
        ),
        "files": files,
    }

    out = samples_dir / "corpus.manifest.json"
    with out.open("w") as f:
        json.dump(manifest, f, indent=2, sort_keys=False)
        f.write("\n")
    print(
        f"  Wrote {out} ({len(files)} file(s), status={snapshot_status})",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
