// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String? getFileManifest({required List<int> fileBytes, required String path}) =>
    RustLib.instance.api.crateApiC2PaGetFileManifest(
      fileBytes: fileBytes,
      path: path,
    );

String? getFileManifestFormat({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetFileManifestFormat(
  fileBytes: fileBytes,
  format: format,
);

String? getManifestWithValidation({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithValidation(
  fileBytes: fileBytes,
  format: format,
);

String? getManifestWithValidationFromPath({
  required List<int> fileBytes,
  required String path,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithValidationFromPath(
  fileBytes: fileBytes,
  path: path,
);

/// Validate a C2PA asset against provided trust anchor PEM bundles.
///
/// `trust_anchors_pem` should contain the C2PA Trust List and optionally
/// the TSA Trust List concatenated as a single PEM bundle.
String? getManifestWithTrustValidation({
  required List<int> fileBytes,
  required String format,
  required String trustAnchorsPem,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithTrustValidation(
  fileBytes: fileBytes,
  format: format,
  trustAnchorsPem: trustAnchorsPem,
);

/// Convenience wrapper that guesses MIME from file path.
String? getManifestWithTrustValidationFromPath({
  required List<int> fileBytes,
  required String path,
  required String trustAnchorsPem,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithTrustValidationFromPath(
  fileBytes: fileBytes,
  path: path,
  trustAnchorsPem: trustAnchorsPem,
);
