// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String getFileManifest({required List<int> fileBytes, required String path}) =>
    RustLib.instance.api.crateApiC2PaGetFileManifest(
      fileBytes: fileBytes,
      path: path,
    );

String getFileManifestFormat({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetFileManifestFormat(
  fileBytes: fileBytes,
  format: format,
);
