// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detached_manifest_json`, `mime_type_from_path`, `normalize_detached_manifest_format`, `read_path_bytes`, `reader_manifest_json_value`

Future<String?> getFileManifest({
  required List<int> fileBytes,
  required String path,
}) => RustLib.instance.api.crateApiC2PaGetFileManifest(
  fileBytes: fileBytes,
  path: path,
);

Future<String?> getFileManifestFormat({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetFileManifestFormat(
  fileBytes: fileBytes,
  format: format,
);

/// UTF-8 JSON bytes for [`get_file_manifest_format`]. See
/// [`get_manifest_with_validation_utf8`] for the web FRB rationale.
Future<Uint8List?> getFileManifestFormatUtf8({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetFileManifestFormatUtf8(
  fileBytes: fileBytes,
  format: format,
);

Future<String?> getManifestWithValidation({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithValidation(
  fileBytes: fileBytes,
  format: format,
);

/// UTF-8 JSON bytes for [`get_manifest_with_validation`].
///
/// Web FRB sync can fail to decode very large [`String`] returns from WASM
/// (Dart `TypeError` on DCO decode). Callers should `utf8.decode` on the VM
/// or web.
Future<Uint8List?> getManifestWithValidationUtf8({
  required List<int> fileBytes,
  required String format,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithValidationUtf8(
  fileBytes: fileBytes,
  format: format,
);

Future<String?> getManifestWithValidationFromPath({required String path}) =>
    RustLib.instance.api.crateApiC2PaGetManifestWithValidationFromPath(
      path: path,
    );

/// Validate a C2PA asset against provided trust anchor PEM bundles.
///
/// `trust_anchors_pem` should contain the C2PA Trust List and optionally
/// the TSA Trust List concatenated as a single PEM bundle.
Future<String?> getManifestWithTrustValidation({
  required List<int> fileBytes,
  required String format,
  required String trustAnchorsPem,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithTrustValidation(
  fileBytes: fileBytes,
  format: format,
  trustAnchorsPem: trustAnchorsPem,
);

/// Convenience wrapper that guesses MIME from file path and reads bytes on the
/// Rust side.
Future<String?> getManifestWithTrustValidationFromPath({
  required String path,
  required String trustAnchorsPem,
}) => RustLib.instance.api.crateApiC2PaGetManifestWithTrustValidationFromPath(
  path: path,
  trustAnchorsPem: trustAnchorsPem,
);

/// Validate a detached manifest store (sidecar JUMBF) against asset bytes.
///
/// Uses `Reader::from_context(context).with_manifest_data_and_stream` so hash
/// binding, signature checks, and `validation_status` match the embedded read
/// path. `manifest_format` is the store MIME (typically `application/c2pa`);
/// `asset_format` is the bound media MIME or extension.
Future<String?> getDetachedManifestWithValidation({
  required List<int> manifestBytes,
  required String manifestFormat,
  required List<int> assetBytes,
  required String assetFormat,
}) => RustLib.instance.api.crateApiC2PaGetDetachedManifestWithValidation(
  manifestBytes: manifestBytes,
  manifestFormat: manifestFormat,
  assetBytes: assetBytes,
  assetFormat: assetFormat,
);

/// UTF-8 JSON bytes for [`get_detached_manifest_with_validation`].
Future<Uint8List?> getDetachedManifestWithValidationUtf8({
  required List<int> manifestBytes,
  required String manifestFormat,
  required List<int> assetBytes,
  required String assetFormat,
}) => RustLib.instance.api.crateApiC2PaGetDetachedManifestWithValidationUtf8(
  manifestBytes: manifestBytes,
  manifestFormat: manifestFormat,
  assetBytes: assetBytes,
  assetFormat: assetFormat,
);

/// Detached manifest read with explicit trust-anchor PEM validation.
Future<String?> getDetachedManifestWithTrustValidation({
  required List<int> manifestBytes,
  required String manifestFormat,
  required List<int> assetBytes,
  required String assetFormat,
  required String trustAnchorsPem,
}) => RustLib.instance.api.crateApiC2PaGetDetachedManifestWithTrustValidation(
  manifestBytes: manifestBytes,
  manifestFormat: manifestFormat,
  assetBytes: assetBytes,
  assetFormat: assetFormat,
  trustAnchorsPem: trustAnchorsPem,
);

/// UTF-8 JSON bytes for [`get_detached_manifest_with_trust_validation`].
Future<Uint8List?> getDetachedManifestWithTrustValidationUtf8({
  required List<int> manifestBytes,
  required String manifestFormat,
  required List<int> assetBytes,
  required String assetFormat,
  required String trustAnchorsPem,
}) =>
    RustLib.instance.api.crateApiC2PaGetDetachedManifestWithTrustValidationUtf8(
      manifestBytes: manifestBytes,
      manifestFormat: manifestFormat,
      assetBytes: assetBytes,
      assetFormat: assetFormat,
      trustAnchorsPem: trustAnchorsPem,
    );
